import { TemplateSection } from '@/types/builder';

export const templateSections: TemplateSection[] = [
  // Navbar Templates
  {
    id: 'navbar-1',
    name: 'Simple Navbar',
    type: 'navbar',
    variant: 'simple',
    thumbnail: '📋',
    defaultData: {
      websiteName: 'Sell Sync',
      logo: 'https://sellsync.netlify.app/assets/FullLogo2-BHrAzKAZ.png',
      links: [
        { id: '1', text: 'Home', href: '#home' },
        { id: '2', text: 'Products', href: '#products' },
        { id: '3', text: 'Blogs', href: '#blogs' },
        { id: '4', text: 'Contact', href: '#contact' },
      ],
      buttons: [
        {
          text: 'Get Started',
          href: '#',
          variant: 'primary' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
    },
  },
  {
    id: 'navbar-2',
    name: 'Centered Navbar',
    type: 'navbar',
    variant: 'centered',
    thumbnail: '🎯',
    defaultData: {
      websiteName: 'Sell Sync',
      logo: 'https://sellsync.netlify.app/assets/FullLogo2-BHrAzKAZ.png',
      links: [
        { id: '1', text: 'Features', href: '#features' },
        { id: '2', text: 'Pricing', href: '#pricing' },
        { id: '3', text: 'Products', href: '#products' },
        { id: '4', text: 'Blogs', href: '#blogs' },
      ],
      buttons: [
        {
          text: 'Sign In',
          href: '#',
          variant: 'ghost' as const,
          size: 'md' as const,
        },
        {
          text: 'Sign Up',
          href: '#',
          variant: 'primary' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
    },
  },
  {
    id: 'navbar-3',
    name: 'Transparent Navbar',
    type: 'navbar',
    variant: 'transparent',
    thumbnail: '✨',
    defaultData: {
      websiteName: 'Sell Sync',
      logo: 'https://sellsync.netlify.app/assets/FullLogo2-BHrAzKAZ.png',
      links: [
        { id: '1', text: 'Home', href: '#home' },
        { id: '2', text: 'Products', href: '#products' },
        { id: '3', text: 'Blogs', href: '#blogs' },
        { id: '4', text: 'Contact', href: '#contact' },
      ],
      buttons: [
        {
          text: 'Get Quote',
          href: '#',
          variant: 'secondary' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: 'transparent',
      textColor: '#000000',
    },
  },
  {
    id: 'navbar-4',
    name: 'Dark Theme Navbar',
    type: 'navbar',
    variant: 'dark',
    thumbnail: '🌙',
    defaultData: {
      websiteName: 'Sell Sync',
      logo: 'https://sellsync.netlify.app/assets/FullLogo2-BHrAzKAZ.png',
      links: [
        { id: '1', text: 'Home', href: '#home' },
        { id: '2', text: 'Products', href: '#products' },
        { id: '3', text: 'Blogs', href: '#blogs' },
        { id: '4', text: 'Contact', href: '#contact' },
      ],
      buttons: [
        {
          text: 'Login',
          href: '#',
          variant: 'ghost' as const,
          size: 'md' as const,
        },
        {
          text: 'Sign Up',
          href: '#',
          variant: 'primary' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#1a1a1a',
      textColor: '#ffffff',
    },
  },
  {
    id: 'navbar-5',
    name: 'Minimalist Navbar',
    type: 'navbar',
    variant: 'minimal',
    thumbnail: '⚪',
    defaultData: {
      websiteName: 'Sell Sync',
      logo: 'https://sellsync.netlify.app/assets/FullLogo2-BHrAzKAZ.png',
      links: [
        { id: '1', text: 'Products', href: '#products' },
        { id: '2', text: 'Blogs', href: '#blogs' },
        { id: '3', text: 'Contact', href: '#contact' },
      ],
      buttons: [
        {
          text: 'Get Started',
          href: '#',
          variant: 'primary' as const,
          size: 'sm' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
    },
  },
  {
    id: 'navbar-6',
    name: 'Boxed Navbar',
    type: 'navbar',
    variant: 'boxed',
    thumbnail: '📦',
    defaultData: {
      websiteName: 'Sell Sync',
      logo: 'https://sellsync.netlify.app/assets/FullLogo2-BHrAzKAZ.png',
      links: [
        { id: '1', text: 'Home', href: '#home' },
        { id: '2', text: 'Products', href: '#products' },
        { id: '3', text: 'Blogs', href: '#blogs' },
        { id: '4', text: 'About', href: '#about' },
        { id: '5', text: 'Contact', href: '#contact' },
      ],
      buttons: [
        {
          text: 'Download',
          href: '#',
          variant: 'secondary' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
    },
  },
  {
    id: 'navbar-7',
    name: 'Split Navigation',
    type: 'navbar',
    variant: 'split',
    thumbnail: '⚡',
    defaultData: {
      websiteName: 'Sell Sync',
      logo: 'https://sellsync.netlify.app/assets/FullLogo2-BHrAzKAZ.png',
      links: [
        { id: '1', text: 'Products', href: '#products' },
        { id: '2', text: 'Pricing', href: '#pricing' },
        { id: '3', text: 'Blogs', href: '#blogs' },
        { id: '4', text: 'Support', href: '#support' },
      ],
      buttons: [
        {
          text: 'Try Free',
          href: '#',
          variant: 'primary' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
    },
  },
  {
    id: 'navbar-8',
    name: 'Navbar with Search',
    type: 'navbar',
    variant: 'with-search',
    thumbnail: '🔍',
    defaultData: {
      websiteName: 'Sell Sync',
      logo: 'https://sellsync.netlify.app/assets/FullLogo2-BHrAzKAZ.png',
      links: [
        { id: '1', text: 'Home', href: '#home' },
        { id: '2', text: 'Products', href: '#products' },
        { id: '3', text: 'Blogs', href: '#blogs' },
        { id: '4', text: 'Resources', href: '#resources' },
      ],
      buttons: [
        {
          text: 'Account',
          href: '#',
          variant: 'outline' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      showSearch: true,
    },
  },

  // Hero Templates
  {
    id: 'hero-1',
    name: 'Centered Hero',
    type: 'hero',
    variant: 'centered',
    thumbnail: '🎯',
    defaultData: {
      heading: 'Build Something Amazing',
      subheading: '✨ Modern Web Development',
      description: 'Create professional websites with cutting-edge technology. Fast, beautiful, and built for success.',
      buttons: [
        {
          text: 'Get Started Free',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
        {
          text: 'See Examples',
          href: '#',
          variant: 'outline' as const,
          size: 'lg' as const,
        },
      ],
      image: {
        src: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
        alt: 'Analytics Dashboard',
      },
      backgroundImage: {
        src: '',
        alt: 'Background Image',
      },
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '100px 24px',
    },
  },
  {
    id: 'hero-2',
    name: 'Split Hero',
    type: 'hero',
    variant: 'split',
    thumbnail: '🎨',
    defaultData: {
      heading: 'Design. Build. Deploy.',
      subheading: '🚀 The Future of Web',
      description: 'Transform your vision into reality with our comprehensive platform. Professional tools, seamless workflow, stunning results.',
      buttons: [
        {
          text: 'Start Your Project',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
        {
          text: 'View Templates',
          href: '#',
          variant: 'ghost' as const,
          size: 'lg' as const,
        },
      ],
      image: {
        src: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&q=80',
        alt: 'Team Collaboration',
      },
      backgroundImage: {
        src: '',
        alt: 'Background Image',
      },
      backgroundColor: '#fafafa',
      textColor: '#0a0a0a',
      padding: '100px 24px',
    },
  },
  {
    id: 'hero-4',
    name: 'Minimal Hero',
    type: 'hero',
    variant: 'minimal',
    thumbnail: '⚪',
    defaultData: {
      heading: 'Simplicity Meets Power',
      description: 'Elegant design. Powerful features. Zero complexity.',
      buttons: [
        {
          text: 'Get Started',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
      ],
      backgroundImage: {
        src: '',
        alt: 'Background Image',
      },
      backgroundColor: '#ffffff',
      textColor: '#171717',
      padding: '140px 24px',
    },
  },
  {
    id: 'hero-5',
    name: 'Gradient Hero',
    type: 'hero',
    variant: 'gradient',
    thumbnail: '🌈',
    defaultData: {
      heading: 'Launch Your Product in Days, Not Months',
      subheading: 'Fast Track Success',
      description: 'Pre-built templates and powerful tools to help you ship faster and grow your business.',
      buttons: [
        {
          text: 'Start Free Trial',
          href: '#',
          variant: 'secondary' as const,
          size: 'lg' as const,
        },
        {
          text: 'See How It Works',
          href: '#',
          variant: 'outline' as const,
          size: 'lg' as const,
        },
      ],
      backgroundImage: {
        src: '',
        alt: 'Background Image',
      },
      backgroundColor: '#6366f1',
      textColor: '#ffffff',
      padding: '100px 24px',
    },
  },
  {
    id: 'hero-6',
    name: 'Video Background Hero',
    type: 'hero',
    variant: 'video',
    thumbnail: '🎬',
    defaultData: {
      heading: 'Experience the Future of Web Design',
      subheading: '✨ Innovation Meets Simplicity',
      description: 'Create stunning, responsive websites with our award-winning platform. Join thousands of creators building the web of tomorrow.',
      buttons: [
        {
          text: 'Watch Demo',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
        {
          text: 'Get Started Free',
          href: '#',
          variant: 'secondary' as const,
          size: 'lg' as const,
        },
      ],
      videoUrl: '',
      backgroundImage: {
        src: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1920&q=80',
        alt: 'Modern Workspace',
      },
      backgroundColor: '#000000',
      textColor: '#ffffff',
      padding: '180px 24px',
    },
  },
  {
    id: 'hero-7',
    name: 'Image Right Hero',
    type: 'hero',
    variant: 'image-right',
    thumbnail: '🖼️',
    defaultData: {
      heading: 'Ship Products Faster',
      subheading: '⚡ Built for Teams',
      description: 'Collaborate seamlessly. Deploy confidently. Scale effortlessly. Everything you need in one powerful platform.',
      buttons: [
        {
          text: 'Start Free Trial',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
        {
          text: 'Watch Demo',
          href: '#',
          variant: 'ghost' as const,
          size: 'lg' as const,
        },
      ],
      image: {
        src: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80',
        alt: 'Team Working Together',
      },
      backgroundImage: {
        src: '',
        alt: 'Background Image',
      },
      backgroundColor: '#ffffff',
      textColor: '#0f172a',
      padding: '100px 24px',
    },
  },
  {
    id: 'hero-8',
    name: 'Full Screen Hero',
    type: 'hero',
    variant: 'fullscreen',
    thumbnail: '📺',
    defaultData: {
      heading: 'Welcome to the Future',
      subheading: '🚀 Next Generation Platform',
      description: 'Discover powerful features designed to transform your workflow and boost productivity like never before.',
      buttons: [
        {
          text: 'Explore Features',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
        {
          text: 'Learn More',
          href: '#',
          variant: 'outline' as const,
          size: 'lg' as const,
        },
      ],
      image: {
        src: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&q=80',
        alt: 'Technology Background',
      },
      backgroundImage: {
        src: '',
        alt: 'Background Image',
      },
      backgroundColor: '#0f172a',
      textColor: '#ffffff',
      padding: '0',
    },
  },
  {
    id: 'hero-9',
    name: 'CTA Focused Hero',
    type: 'hero',
    variant: 'cta-focused',
    thumbnail: '🎯',
    defaultData: {
      heading: 'Get 50% Off Your First Month',
      subheading: 'Limited Time Offer',
      description: 'Join thousands of happy customers who have transformed their business with our platform.',
      buttons: [
        {
          text: 'Claim Your Discount',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
      ],
      stats: [
        { value: '50K+', label: 'Active Users' },
        { value: '4.9/5', label: 'Customer Rating' },
        { value: '99.9%', label: 'Uptime' },
      ],
      backgroundImage: {
        src: '',
        alt: 'Background Image',
      },
      backgroundColor: '#10b981',
      textColor: '#ffffff',
      padding: '100px 24px',
    },
  },

  // Products Templates
  {
    id: 'products-1',
    name: 'Product Grid',
    type: 'products',
    variant: 'grid',
    thumbnail: '🛍️',
    defaultData: {
      heading: 'Featured Products',
      description: 'Discover our curated selection of premium items',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          description: 'Premium noise-cancelling headphones with exceptional sound quality',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          category: 'Electronics',
          inStock: true,
        },
        {
          id: '2',
          name: 'Smart Watch Pro',
          price: '349.99',
          description: 'Advanced fitness tracking and smart notifications',
          image: { src: '/assets/product-2.jpg', alt: 'Smart Watch' },
          category: 'Electronics',
          inStock: true,
        },
        {
          id: '3',
          name: 'Premium Backpack',
          price: '89.99',
          description: 'Durable and stylish backpack for everyday adventures',
          image: { src: '/assets/product-3.jpg', alt: 'Premium Backpack' },
          category: 'Accessories',
          inStock: true,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'products-2',
    name: 'Product Carousel',
    type: 'products',
    variant: 'carousel',
    thumbnail: '🎠',
    defaultData: {
      heading: 'Best Sellers',
      description: 'Our most popular products loved by customers',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          description: 'Premium noise-cancelling headphones with exceptional sound quality',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          rating: 4.8,
          reviews: 245,
          inStock: true,
        },
        {
          id: '2',
          name: 'Smart Watch Pro',
          price: '349.99',
          description: 'Advanced fitness tracking and smart notifications',
          image: { src: '/assets/product-2.jpg', alt: 'Smart Watch' },
          rating: 4.9,
          reviews: 189,
          inStock: true,
        },
        {
          id: '3',
          name: 'Premium Backpack',
          price: '89.99',
          description: 'Durable and stylish backpack for everyday adventures',
          image: { src: '/assets/product-3.jpg', alt: 'Premium Backpack' },
          rating: 4.7,
          reviews: 312,
          inStock: true,
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'products-3',
    name: 'Featured Product',
    type: 'products',
    variant: 'featured',
    thumbnail: '⭐',
    defaultData: {
      heading: 'Product of the Month',
      description: 'Exclusive deal on our premium selection',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          originalPrice: '179.99',
          description: 'Experience superior sound quality with our flagship wireless headphones. Features active noise cancellation, 30-hour battery life, and premium comfort design.',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          features: [
            'Active Noise Cancellation',
            '30-Hour Battery Life',
            'Premium Leather Cushions',
            'Bluetooth 5.0',
          ],
          rating: 4.8,
          reviews: 245,
          inStock: true,
        },
      ],
      buttons: [
        {
          text: 'Add to Cart',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
        {
          text: 'View Details',
          href: '#',
          variant: 'outline' as const,
          size: 'lg' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'products-4',
    name: 'Gradient Products',
    type: 'products',
    variant: 'gradient',
    thumbnail: '🌈',
    defaultData: {
      heading: 'Trending Now',
      description: 'Discover our hottest products with exclusive deals',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          description: 'Premium noise-cancelling headphones with exceptional sound quality',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          rating: 4.8,
          reviews: 245,
          inStock: true,
        },
        {
          id: '2',
          name: 'Smart Watch Pro',
          price: '349.99',
          description: 'Advanced fitness tracking and smart notifications',
          image: { src: '/assets/product-2.jpg', alt: 'Smart Watch' },
          rating: 4.9,
          reviews: 189,
          inStock: true,
        },
        {
          id: '3',
          name: 'Premium Backpack',
          price: '89.99',
          description: 'Durable and stylish backpack for everyday adventures',
          image: { src: '/assets/product-3.jpg', alt: 'Premium Backpack' },
          rating: 4.7,
          reviews: 312,
          inStock: true,
        },
      ],
      backgroundColor: '#6366f1',
      textColor: '#ffffff',
      padding: '100px 24px',
    },
  },
  {
    id: 'products-5',
    name: 'Fullscreen Products',
    type: 'products',
    variant: 'fullscreen',
    thumbnail: '📺',
    defaultData: {
      heading: 'Premium Collection',
      description: 'Explore our exclusive range of premium products',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          description: 'Premium noise-cancelling headphones with exceptional sound quality',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          inStock: true,
        },
        {
          id: '2',
          name: 'Smart Watch Pro',
          price: '349.99',
          description: 'Advanced fitness tracking and smart notifications',
          image: { src: '/assets/product-2.jpg', alt: 'Smart Watch' },
          inStock: true,
        },
        {
          id: '3',
          name: 'Premium Backpack',
          price: '89.99',
          description: 'Durable and stylish backpack for everyday adventures',
          image: { src: '/assets/product-3.jpg', alt: 'Premium Backpack' },
          inStock: true,
        },
      ],
      backgroundColor: '#000000',
      textColor: '#ffffff',
      padding: '0',
    },
  },
  {
    id: 'products-6',
    name: 'Minimal Products',
    type: 'products',
    variant: 'minimal',
    thumbnail: '⚪',
    defaultData: {
      heading: 'Our Products',
      description: 'Simple, elegant, and functional',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          description: 'Premium noise-cancelling headphones with exceptional sound quality',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          inStock: true,
        },
        {
          id: '2',
          name: 'Smart Watch Pro',
          price: '349.99',
          description: 'Advanced fitness tracking and smart notifications',
          image: { src: '/assets/product-2.jpg', alt: 'Smart Watch' },
          inStock: true,
        },
        {
          id: '3',
          name: 'Premium Backpack',
          price: '89.99',
          description: 'Durable and stylish backpack for everyday adventures',
          image: { src: '/assets/product-3.jpg', alt: 'Premium Backpack' },
          inStock: true,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '140px 24px',
    },
  },
  {
    id: 'products-7',
    name: 'CTA-Focused Products',
    type: 'products',
    variant: 'cta-focused',
    thumbnail: '🎯',
    defaultData: {
      heading: 'Limited Time Offer',
      description: 'Get up to 50% off on selected items',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          originalPrice: '179.99',
          description: 'Premium noise-cancelling headphones with exceptional sound quality',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          rating: 4.8,
          reviews: 245,
          inStock: true,
        },
        {
          id: '2',
          name: 'Smart Watch Pro',
          price: '349.99',
          originalPrice: '449.99',
          description: 'Advanced fitness tracking and smart notifications',
          image: { src: '/assets/product-2.jpg', alt: 'Smart Watch' },
          rating: 4.9,
          reviews: 189,
          inStock: true,
        },
        {
          id: '3',
          name: 'Premium Backpack',
          price: '89.99',
          originalPrice: '119.99',
          description: 'Durable and stylish backpack for everyday adventures',
          image: { src: '/assets/product-3.jpg', alt: 'Premium Backpack' },
          rating: 4.7,
          reviews: 312,
          inStock: true,
        },
      ],
      backgroundColor: '#10b981',
      textColor: '#ffffff',
      padding: '100px 24px',
    },
  },
  {
    id: 'products-8',
    name: 'Split Products',
    type: 'products',
    variant: 'split',
    thumbnail: '⚡',
    defaultData: {
      heading: 'Shop Our Collection',
      description: 'Quality products for modern living',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          description: 'Premium noise-cancelling headphones with exceptional sound quality',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          inStock: true,
        },
        {
          id: '2',
          name: 'Smart Watch Pro',
          price: '349.99',
          description: 'Advanced fitness tracking and smart notifications',
          image: { src: '/assets/product-2.jpg', alt: 'Smart Watch' },
          inStock: true,
        },
        {
          id: '3',
          name: 'Premium Backpack',
          price: '89.99',
          description: 'Durable and stylish backpack for everyday adventures',
          image: { src: '/assets/product-3.jpg', alt: 'Premium Backpack' },
          inStock: true,
        },
      ],
      buttons: [
        {
          text: 'View All Products',
          href: '#',
          variant: 'primary' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '100px 24px',
    },
  },
  {
    id: 'products-9',
    name: 'Image-Right Products',
    type: 'products',
    variant: 'image-right',
    thumbnail: '🖼️',
    defaultData: {
      heading: 'More Products',
      description: 'Explore our full range',
      items: [
        {
          id: '1',
          name: 'Wireless Headphones',
          price: '129.99',
          originalPrice: '179.99',
          description: 'Experience superior sound quality with our flagship wireless headphones. Features active noise cancellation, 30-hour battery life, and premium comfort design.',
          image: { src: '/assets/product-1.jpg', alt: 'Wireless Headphones' },
          rating: 4.8,
          reviews: 245,
          inStock: true,
        },
        {
          id: '2',
          name: 'Smart Watch Pro',
          price: '349.99',
          description: 'Advanced fitness tracking and smart notifications',
          image: { src: '/assets/product-2.jpg', alt: 'Smart Watch' },
          inStock: true,
        },
        {
          id: '3',
          name: 'Premium Backpack',
          price: '89.99',
          description: 'Durable and stylish backpack for everyday adventures',
          image: { src: '/assets/product-3.jpg', alt: 'Premium Backpack' },
          inStock: true,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '100px 24px',
    },
  },

  // Features Templates
  {
    id: 'features-1',
    name: '3-Column Features',
    type: 'features',
    variant: 'three-column',
    thumbnail: '⚡',
    defaultData: {
      heading: 'Powerful Features',
      description: 'Everything you need to build a professional website',
      items: [
        {
          id: '1',
          icon: 'Zap',
          title: 'Lightning Fast',
          description: 'Optimized performance for blazing fast load times',
        },
        {
          id: '2',
          icon: 'Shield',
          title: 'Secure & Reliable',
          description: 'Enterprise-grade security built into every component',
        },
        {
          id: '3',
          icon: 'Palette',
          title: 'Fully Customizable',
          description: 'Customize every aspect to match your brand perfectly',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'features-2',
    name: '2-Column Features',
    type: 'features',
    variant: 'two-column',
    thumbnail: '📱',
    defaultData: {
      heading: 'Built for Modern Teams',
      description: 'Collaborate seamlessly with powerful tools',
      items: [
        {
          id: '1',
          icon: 'Users',
          title: 'Team Collaboration',
          description: 'Work together in real-time with your team members',
        },
        {
          id: '2',
          icon: 'Globe',
          title: 'Global Access',
          description: 'Access your projects from anywhere in the world',
        },
        {
          id: '3',
          icon: 'Smartphone',
          title: 'Mobile Ready',
          description: 'Fully responsive designs that work on any device',
        },
        {
          id: '4',
          icon: 'Cloud',
          title: 'Cloud Storage',
          description: 'Secure cloud storage for all your assets',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'features-3',
    name: 'Icon Left Features',
    type: 'features',
    variant: 'icon-left',
    thumbnail: '👈',
    defaultData: {
      heading: 'Why Choose Us',
      description: 'Discover what makes us different',
      items: [
        {
          id: '1',
          icon: 'Star',
          title: 'Premium Quality',
          description: 'Hand-crafted designs with attention to every detail',
        },
        {
          id: '2',
          icon: 'Headphones',
          title: '24/7 Support',
          description: 'Get help whenever you need it from our expert team',
        },
        {
          id: '3',
          icon: 'Award',
          title: 'Industry Leader',
          description: 'Trusted by thousands of businesses worldwide',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'features-4',
    name: '4-Column Features',
    type: 'features',
    variant: 'four-column',
    thumbnail: '🔥',
    defaultData: {
      heading: 'Comprehensive Solutions',
      description: 'All the tools you need in one place',
      items: [
        {
          id: '1',
          icon: 'Rocket',
          title: 'Fast Deployment',
          description: 'Deploy your website in minutes, not hours',
        },
        {
          id: '2',
          icon: 'Lock',
          title: 'Advanced Security',
          description: 'Protect your data with cutting-edge encryption',
        },
        {
          id: '3',
          icon: 'BarChart3',
          title: 'Analytics',
          description: 'Track performance with detailed insights',
        },
        {
          id: '4',
          icon: 'Heart',
          title: 'User Friendly',
          description: 'Intuitive interface designed for everyone',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'features-5',
    name: 'Features with Images',
    type: 'features',
    variant: 'with-images',
    thumbnail: '🖼️',
    defaultData: {
      heading: 'Visual Features',
      description: 'See our features in action',
      items: [
        {
          id: '1',
          icon: 'Image',
          title: 'Visual Builder',
          description: 'Drag and drop to create stunning layouts',
          image: { src: '/assets/feature-1.jpg', alt: 'Visual Builder' },
        },
        {
          id: '2',
          icon: 'Code',
          title: 'Code Export',
          description: 'Export clean, optimized code for production',
          image: { src: '/assets/feature-2.jpg', alt: 'Code Export' },
        },
        {
          id: '3',
          icon: 'Share',
          title: 'Easy Sharing',
          description: 'Share your designs with team members instantly',
          image: { src: '/assets/feature-3.jpg', alt: 'Easy Sharing' },
        },
      ],
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'features-6',
    name: 'Centered Features',
    type: 'features',
    variant: 'centered',
    thumbnail: '🎯',
    defaultData: {
      heading: 'Centered Excellence',
      description: 'Features that put you at the center',
      items: [
        {
          id: '1',
          icon: 'Target',
          title: 'Focused Approach',
          description: 'Tailored solutions for your specific needs',
        },
        {
          id: '2',
          icon: 'TrendingUp',
          title: 'Scalable Growth',
          description: 'Grow your business with scalable features',
        },
        {
          id: '3',
          icon: 'CheckCircle',
          title: 'Reliable Performance',
          description: 'Consistent results you can count on',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // About Templates
  {
    id: 'about-1',
    name: 'About - Image Left',
    type: 'about',
    variant: 'image-left',
    thumbnail: '👥',
    defaultData: {
      heading: 'About Our Company',
      description: 'We are passionate about helping businesses create stunning online experiences. Our platform empowers users to build professional websites without any coding knowledge.',
      image: {
        src: '/assets/about-default.jpg',
        alt: 'About Us',
      },
      buttons: [
        {
          text: 'Learn More',
          href: '#',
          variant: 'primary' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'about-2',
    name: 'About - Image Right',
    type: 'about',
    variant: 'image-right',
    thumbnail: '👤',
    defaultData: {
      heading: 'Our Story',
      description: 'Founded with a vision to democratize web design, we\'ve helped thousands of businesses establish their online presence. Our journey started with a simple idea: everyone deserves a beautiful website.',
      image: {
        src: '/assets/about-default.jpg',
        alt: 'Our Story',
      },
      buttons: [
        {
          text: 'Read More',
          href: '#',
          variant: 'primary' as const,
          size: 'md' as const,
        },
        {
          text: 'Contact Us',
          href: '#',
          variant: 'outline' as const,
          size: 'md' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'about-3',
    name: 'Centered About',
    type: 'about',
    variant: 'centered',
    thumbnail: '🎯',
    defaultData: {
      heading: 'Who We Are',
      description: 'We are a team of passionate designers and developers committed to creating exceptional digital experiences. Our mission is to empower businesses of all sizes to establish a strong online presence.',
      buttons: [
        {
          text: 'Get Started',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
        {
          text: 'Our Work',
          href: '#',
          variant: 'outline' as const,
          size: 'lg' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'about-4',
    name: 'About with Stats',
    type: 'about',
    variant: 'with-stats',
    thumbnail: '📊',
    defaultData: {
      heading: 'Our Impact in Numbers',
      description: 'Since our founding, we\'ve been dedicated to delivering exceptional results for our clients. Here\'s what we\'ve achieved together.',
      stats: [
        { value: '500+', label: 'Projects Completed' },
        { value: '98%', label: 'Client Satisfaction' },
        { value: '50+', label: 'Team Members' },
        { value: '24/7', label: 'Support Available' },
      ],
      buttons: [
        {
          text: 'View Our Work',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
      ],
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'about-5',
    name: 'Minimal About',
    type: 'about',
    variant: 'minimal',
    thumbnail: '⚪',
    defaultData: {
      heading: 'Simplicity in Action',
      description: 'We believe in the power of clean design and thoughtful solutions. Every project we undertake reflects our commitment to excellence and attention to detail.',
      buttons: [
        {
          text: 'Learn More',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '140px 24px',
    },
  },
  {
    id: 'about-6',
    name: 'About with Timeline',
    type: 'about',
    variant: 'timeline',
    thumbnail: '📅',
    defaultData: {
      heading: 'Our Journey',
      description: 'From humble beginnings to industry leaders, our story is one of innovation, dedication, and continuous growth.',
      timeline: [
        {
          year: '2018',
          title: 'Company Founded',
          description: 'Started with a vision to revolutionize web design',
        },
        {
          year: '2019',
          title: 'First Major Client',
          description: 'Landed our first enterprise client',
        },
        {
          year: '2020',
          title: 'Team Expansion',
          description: 'Grew to 20+ talented professionals',
        },
        {
          year: '2021',
          title: 'Product Launch',
          description: 'Released our flagship platform',
        },
      ],
      buttons: [
        {
          text: 'Join Our Team',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // Services Templates
  {
    id: 'services-1',
    name: 'Service Grid',
    type: 'services',
    variant: 'grid',
    thumbnail: '💼',
    defaultData: {
      heading: 'Our Services',
      description: 'Comprehensive solutions for your digital needs',
      items: [
        {
          id: '1',
          image: { src: '/assets/service-1.jpg', alt: 'Web Development' },
          title: 'Web Development',
          description: 'Custom websites built with modern technologies',
          link: '#',
        },
        {
          id: '2',
          image: { src: '/assets/service-2.jpg', alt: 'Mobile Apps' },
          title: 'Mobile Apps',
          description: 'Native and cross-platform mobile solutions',
          link: '#',
        },
        {
          id: '3',
          image: { src: '/assets/service-3.jpg', alt: 'Branding' },
          title: 'Branding & Design',
          description: 'Complete brand identity and design services',
          link: '#',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'services-2',
    name: 'Service List',
    type: 'services',
    variant: 'list',
    thumbnail: '📝',
    defaultData: {
      heading: 'What We Offer',
      description: 'Professional services tailored to your needs',
      items: [
        {
          id: '1',
          icon: 'Code',
          title: 'Custom Development',
          description: 'Tailored solutions built specifically for your business requirements',
          link: '#',
        },
        {
          id: '2',
          icon: 'Paintbrush',
          title: 'UI/UX Design',
          description: 'Beautiful, intuitive interfaces that users love',
          link: '#',
        },
        {
          id: '3',
          icon: 'Rocket',
          title: 'Launch & Deploy',
          description: 'Get your project live with our deployment support',
          link: '#',
        },
        {
          id: '4',
          icon: 'BarChart',
          title: 'Analytics & SEO',
          description: 'Optimize your site for search engines and track performance',
          link: '#',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  {
    id: 'services-3',
    name: 'Services with Cards',
    type: 'services',
    variant: 'cards',
    thumbnail: '🃏',
    defaultData: {
      heading: 'Our Expertise',
      description: 'Delivering exceptional results across multiple domains',
      items: [
        {
          id: '1',
          icon: 'Globe',
          title: 'Digital Strategy',
          description: 'Strategic planning and digital transformation consulting',
          link: '#',
        },
        {
          id: '2',
          icon: 'Smartphone',
          title: 'Mobile Solutions',
          description: 'iOS and Android app development with cutting-edge technology',
          link: '#',
        },
        {
          id: '3',
          icon: 'Cloud',
          title: 'Cloud Services',
          description: 'Scalable cloud infrastructure and migration services',
          link: '#',
        },
        {
          id: '4',
          icon: 'Shield',
          title: 'Cybersecurity',
          description: 'Comprehensive security solutions and compliance management',
          link: '#',
        },
        {
          id: '5',
          icon: 'TrendingUp',
          title: 'Data Analytics',
          description: 'Business intelligence and data-driven insights',
          link: '#',
        },
        {
          id: '6',
          icon: 'Users',
          title: 'Consulting',
          description: 'Expert guidance and technical consulting services',
          link: '#',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'services-4',
    name: 'Services with Icons',
    type: 'services',
    variant: 'icons',
    thumbnail: '🎯',
    defaultData: {
      heading: 'What We Do',
      description: 'Comprehensive service offerings designed for modern businesses',
      items: [
        {
          id: '1',
          icon: 'Code2',
          title: 'Software Development',
          description: 'Full-stack development with modern frameworks',
        },
        {
          id: '2',
          icon: 'Palette',
          title: 'Design Services',
          description: 'Creative design solutions for digital products',
        },
        {
          id: '3',
          icon: 'Database',
          title: 'Database Design',
          description: 'Optimized database architecture and management',
        },
        {
          id: '4',
          icon: 'Zap',
          title: 'Performance Optimization',
          description: 'Speed and efficiency improvements for applications',
        },
        {
          id: '5',
          icon: 'Headphones',
          title: 'Technical Support',
          description: '24/7 technical assistance and maintenance',
        },
        {
          id: '6',
          icon: 'Target',
          title: 'Quality Assurance',
          description: 'Comprehensive testing and quality control',
        },
      ],
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'services-5',
    name: 'Minimal Services',
    type: 'services',
    variant: 'minimal',
    thumbnail: '⚪',
    defaultData: {
      heading: 'Our Services',
      description: 'Focused solutions for your business needs',
      items: [
        {
          id: '1',
          title: 'Web Development',
          description: 'Modern, responsive websites built with the latest technologies',
        },
        {
          id: '2',
          title: 'Mobile Apps',
          description: 'Native and cross-platform mobile applications',
        },
        {
          id: '3',
          title: 'Digital Marketing',
          description: 'Strategic marketing campaigns that drive results',
        },
        {
          id: '4',
          title: 'E-commerce',
          description: 'Complete online store setup and management',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '140px 24px',
    },
  },
  {
    id: 'services-6',
    name: 'Services with Process',
    type: 'services',
    variant: 'process',
    thumbnail: '🔄',
    defaultData: {
      heading: 'Our Process',
      description: 'How we deliver exceptional results for our clients',
      items: [
        {
          id: '1',
          icon: 'Search',
          title: 'Discovery',
          description: 'Understanding your needs and goals through detailed consultation',
          step: '01',
        },
        {
          id: '2',
          icon: 'Lightbulb',
          title: 'Strategy',
          description: 'Developing a comprehensive plan tailored to your objectives',
          step: '02',
        },
        {
          id: '3',
          icon: 'Wrench',
          title: 'Development',
          description: 'Building your solution with attention to detail and quality',
          step: '03',
        },
        {
          id: '4',
          icon: 'CheckCircle',
          title: 'Launch',
          description: 'Deploying your project and ensuring everything works perfectly',
          step: '04',
        },
        {
          id: '5',
          icon: 'BarChart',
          title: 'Support',
          description: 'Ongoing maintenance and support to keep your project running smoothly',
          step: '05',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // Gallery Templates
  {
    id: 'gallery-1',
    name: 'Photo Grid',
    type: 'gallery',
    variant: 'grid',
    thumbnail: '🖼️',
    defaultData: {
      heading: 'Our Work',
      items: [
        {
          id: '1',
          image: { src: '/assets/service-1.jpg', alt: 'Project 1' },
          title: 'Project Alpha',
        },
        {
          id: '2',
          image: { src: '/assets/service-2.jpg', alt: 'Project 2' },
          title: 'Project Beta',
        },
        {
          id: '3',
          image: { src: '/assets/service-3.jpg', alt: 'Project 3' },
          title: 'Project Gamma',
        },
        {
          id: '4',
          image: { src: '/assets/about-default.jpg', alt: 'Project 4' },
          title: 'Project Delta',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'gallery-2',
    name: 'Masonry Gallery',
    type: 'gallery',
    variant: 'masonry',
    thumbnail: '🎨',
    defaultData: {
      heading: 'Portfolio Showcase',
      description: 'Browse through our recent projects',
      items: [
        {
          id: '1',
          image: { src: '/assets/hero-default.jpg', alt: 'Project 1' },
          title: 'Brand Identity',
        },
        {
          id: '2',
          image: { src: '/assets/service-1.jpg', alt: 'Project 2' },
          title: 'Web Design',
        },
        {
          id: '3',
          image: { src: '/assets/service-2.jpg', alt: 'Project 3' },
          title: 'Mobile App',
        },
        {
          id: '4',
          image: { src: '/assets/service-3.jpg', alt: 'Project 4' },
          title: 'Marketing',
        },
        {
          id: '5',
          image: { src: '/assets/about-default.jpg', alt: 'Project 5' },
          title: 'Photography',
        },
        {
          id: '6',
          image: { src: '/assets/hero-default.jpg', alt: 'Project 6' },
          title: 'Video Production',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  {
    id: 'gallery-3',
    name: 'Gallery with Lightbox',
    type: 'gallery',
    variant: 'lightbox',
    thumbnail: '💡',
    defaultData: {
      heading: 'Project Showcase',
      description: 'Click on any image to view in full detail',
      items: [
        {
          id: '1',
          image: { src: '/assets/hero-default.jpg', alt: 'Project 1' },
          title: 'E-commerce Platform',
          description: 'A complete online shopping solution',
        },
        {
          id: '2',
          image: { src: '/assets/service-1.jpg', alt: 'Project 2' },
          title: 'Corporate Website',
          description: 'Professional business website design',
        },
        {
          id: '3',
          image: { src: '/assets/service-2.jpg', alt: 'Project 3' },
          title: 'Mobile Application',
          description: 'Cross-platform mobile app development',
        },
        {
          id: '4',
          image: { src: '/assets/service-3.jpg', alt: 'Project 4' },
          title: 'Brand Identity',
          description: 'Complete branding and visual identity',
        },
        {
          id: '5',
          image: { src: '/assets/about-default.jpg', alt: 'Project 5' },
          title: 'Digital Marketing',
          description: 'Comprehensive online marketing campaign',
        },
        {
          id: '6',
          image: { src: '/assets/hero-default.jpg', alt: 'Project 6' },
          title: 'Content Creation',
          description: 'Creative content and media production',
        },
      ],
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'gallery-4',
    name: 'Minimal Gallery',
    type: 'gallery',
    variant: 'minimal',
    thumbnail: '⚪',
    defaultData: {
      heading: 'Portfolio',
      items: [
        {
          id: '1',
          image: { src: '/assets/service-1.jpg', alt: 'Work 1' },
          title: 'Minimal Design',
        },
        {
          id: '2',
          image: { src: '/assets/service-2.jpg', alt: 'Work 2' },
          title: 'Clean Layout',
        },
        {
          id: '3',
          image: { src: '/assets/service-3.jpg', alt: 'Work 3' },
          title: 'Simple Focus',
        },
        {
          id: '4',
          image: { src: '/assets/about-default.jpg', alt: 'Work 4' },
          title: 'Elegant Style',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '140px 24px',
    },
  },
  {
    id: 'gallery-5',
    name: 'Gallery with Categories',
    type: 'gallery',
    variant: 'categories',
    thumbnail: '📂',
    defaultData: {
      heading: 'Our Projects',
      description: 'Explore our work across different categories',
      categories: ['All', 'Web Design', 'Mobile Apps', 'Branding', 'Photography'],
      items: [
        {
          id: '1',
          image: { src: '/assets/hero-default.jpg', alt: 'Web Design Project' },
          title: 'Corporate Website',
          category: 'Web Design',
        },
        {
          id: '2',
          image: { src: '/assets/service-1.jpg', alt: 'Mobile App' },
          title: 'Fitness Tracker App',
          category: 'Mobile Apps',
        },
        {
          id: '3',
          image: { src: '/assets/service-2.jpg', alt: 'Branding Project' },
          title: 'Logo & Brand Identity',
          category: 'Branding',
        },
        {
          id: '4',
          image: { src: '/assets/service-3.jpg', alt: 'Photography' },
          title: 'Product Photography',
          category: 'Photography',
        },
        {
          id: '5',
          image: { src: '/assets/about-default.jpg', alt: 'Web Project' },
          title: 'E-commerce Store',
          category: 'Web Design',
        },
        {
          id: '6',
          image: { src: '/assets/hero-default.jpg', alt: 'Mobile Project' },
          title: 'Social Media App',
          category: 'Mobile Apps',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'gallery-6',
    name: 'Gallery Carousel',
    type: 'gallery',
    variant: 'carousel',
    thumbnail: '🎠',
    defaultData: {
      heading: 'Featured Work',
      description: 'Swipe through our latest projects',
      items: [
        {
          id: '1',
          image: { src: '/assets/hero-default.jpg', alt: 'Featured Project 1' },
          title: 'Modern Web Application',
          description: 'A cutting-edge web application with advanced features',
        },
        {
          id: '2',
          image: { src: '/assets/service-1.jpg', alt: 'Featured Project 2' },
          title: 'Mobile Banking App',
          description: 'Secure and user-friendly mobile banking solution',
        },
        {
          id: '3',
          image: { src: '/assets/service-2.jpg', alt: 'Featured Project 3' },
          title: 'Brand Redesign',
          description: 'Complete brand transformation for a tech startup',
        },
        {
          id: '4',
          image: { src: '/assets/service-3.jpg', alt: 'Featured Project 4' },
          title: 'E-learning Platform',
          description: 'Interactive online learning platform for professionals',
        },
        {
          id: '5',
          image: { src: '/assets/about-default.jpg', alt: 'Featured Project 5' },
          title: 'Restaurant Website',
          description: 'Beautiful website design for a fine dining restaurant',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // Blog Templates
  {
    id: 'blog-1',
    name: 'Blog Grid',
    type: 'blog',
    variant: 'grid',
    thumbnail: '📝',
    defaultData: {
      heading: 'Latest from Our Blog',
      description: 'Insights, tips, and stories from our team',
      items: [
        {
          id: '1',
          title: 'Getting Started with Web Development in 2024',
          excerpt: 'Learn the essential tools and technologies you need to become a successful web developer this year.',
          image: { src: '/assets/blog-1.jpg', alt: 'Web Development' },
          author: 'Sarah Johnson',
          date: 'Dec 1, 2024',
          category: 'Technology',
          readTime: '5 min read',
        },
        {
          id: '2',
          title: 'Building a Successful Business Online',
          excerpt: 'Discover the strategies that helped thousands of entrepreneurs launch and grow their online businesses.',
          image: { src: '/assets/blog-2.jpg', alt: 'Business Growth' },
          author: 'Mike Chen',
          date: 'Nov 28, 2024',
          category: 'Business',
          readTime: '8 min read',
        },
        {
          id: '3',
          title: 'Design Trends That Will Shape 2024',
          excerpt: 'Explore the latest design trends and how to implement them in your next project.',
          image: { src: '/assets/blog-3.jpg', alt: 'Design Trends' },
          author: 'Emily Davis',
          date: 'Nov 25, 2024',
          category: 'Design',
          readTime: '6 min read',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'blog-2',
    name: 'Blog List',
    type: 'blog',
    variant: 'list',
    thumbnail: '📋',
    defaultData: {
      heading: 'Recent Articles',
      description: 'Stay updated with our latest insights and updates',
      items: [
        {
          id: '1',
          title: 'Getting Started with Web Development in 2024',
          excerpt: 'Learn the essential tools and technologies you need to become a successful web developer this year. We cover everything from HTML basics to modern frameworks.',
          image: { src: '/assets/blog-1.jpg', alt: 'Web Development' },
          author: 'Sarah Johnson',
          date: 'Dec 1, 2024',
          category: 'Technology',
          readTime: '5 min read',
        },
        {
          id: '2',
          title: 'Building a Successful Business Online',
          excerpt: 'Discover the strategies that helped thousands of entrepreneurs launch and grow their online businesses. From marketing to scaling, we cover it all.',
          image: { src: '/assets/blog-2.jpg', alt: 'Business Growth' },
          author: 'Mike Chen',
          date: 'Nov 28, 2024',
          category: 'Business',
          readTime: '8 min read',
        },
        {
          id: '3',
          title: 'Design Trends That Will Shape 2024',
          excerpt: 'Explore the latest design trends and how to implement them in your next project. Stay ahead of the curve with expert insights.',
          image: { src: '/assets/blog-3.jpg', alt: 'Design Trends' },
          author: 'Emily Davis',
          date: 'Nov 25, 2024',
          category: 'Design',
          readTime: '6 min read',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'blog-3',
    name: 'Featured Blog',
    type: 'blog',
    variant: 'featured',
    thumbnail: '⭐',
    defaultData: {
      heading: 'Featured Article',
      description: 'Our most popular post this month',
      items: [
        {
          id: '1',
          title: 'The Complete Guide to Building Modern Web Applications',
          excerpt: 'A comprehensive guide covering everything from planning and design to deployment and scaling. Perfect for developers at any skill level.',
          image: { src: '/assets/blog-1.jpg', alt: 'Web Development Guide' },
          author: 'Sarah Johnson',
          date: 'Dec 1, 2024',
          category: 'Technology',
          readTime: '15 min read',
          featured: true,
        },
      ],
      buttons: [
        {
          text: 'Read Article',
          href: '#',
          variant: 'primary' as const,
          size: 'lg' as const,
        },
        {
          text: 'View All Posts',
          href: '#',
          variant: 'outline' as const,
          size: 'lg' as const,
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'blog-4',
    name: 'Blog Cards',
    type: 'blog',
    variant: 'cards',
    thumbnail: '🃏',
    defaultData: {
      heading: 'Blog Posts',
      description: 'Discover our latest insights and stories',
      items: [
        {
          id: '1',
          title: 'Getting Started with Web Development in 2024',
          excerpt: 'Learn the essential tools and technologies you need to become a successful web developer this year.',
          image: { src: '/assets/blog-1.jpg', alt: 'Web Development' },
          author: 'Sarah Johnson',
          date: 'Dec 1, 2024',
          category: 'Technology',
          readTime: '5 min read',
        },
        {
          id: '2',
          title: 'Building a Successful Business Online',
          excerpt: 'Discover the strategies that helped thousands of entrepreneurs launch and grow their online businesses.',
          image: { src: '/assets/blog-2.jpg', alt: 'Business Growth' },
          author: 'Mike Chen',
          date: 'Nov 28, 2024',
          category: 'Business',
          readTime: '8 min read',
        },
        {
          id: '3',
          title: 'Design Trends That Will Shape 2024',
          excerpt: 'Explore the latest design trends and how to implement them in your next project.',
          image: { src: '/assets/blog-3.jpg', alt: 'Design Trends' },
          author: 'Emily Davis',
          date: 'Nov 25, 2024',
          category: 'Design',
          readTime: '6 min read',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'blog-5',
    name: 'Minimal Blog',
    type: 'blog',
    variant: 'minimal',
    thumbnail: '✨',
    defaultData: {
      heading: 'Thoughts & Ideas',
      description: 'Simple insights from our team',
      items: [
        {
          id: '1',
          title: 'The Art of Clean Code',
          excerpt: 'Writing maintainable and readable code is an art that every developer should master.',
          author: 'Alex Rivera',
          date: 'Dec 3, 2024',
          category: 'Development',
          readTime: '4 min read',
        },
        {
          id: '2',
          title: 'Finding Your Creative Flow',
          excerpt: 'How to overcome creative blocks and maintain productivity in your work.',
          author: 'Lisa Wang',
          date: 'Nov 30, 2024',
          category: 'Creativity',
          readTime: '6 min read',
        },
        {
          id: '3',
          title: 'The Future of Remote Work',
          excerpt: 'Exploring how remote work is reshaping the modern workplace.',
          author: 'David Kim',
          date: 'Nov 27, 2024',
          category: 'Business',
          readTime: '7 min read',
        },
      ],
      backgroundColor: '#fafafa',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'blog-6',
    name: 'Blog with Categories',
    type: 'blog',
    variant: 'categories',
    thumbnail: '🏷️',
    defaultData: {
      heading: 'Browse by Category',
      description: 'Explore our articles organized by topic',
      categories: [
        { id: '1', name: 'Technology', count: 12 },
        { id: '2', name: 'Design', count: 8 },
        { id: '3', name: 'Business', count: 6 },
        { id: '4', name: 'Tutorials', count: 15 },
      ],
      items: [
        {
          id: '1',
          title: 'Getting Started with Web Development in 2024',
          excerpt: 'Learn the essential tools and technologies you need to become a successful web developer this year.',
          image: { src: '/assets/blog-1.jpg', alt: 'Web Development' },
          author: 'Sarah Johnson',
          date: 'Dec 1, 2024',
          category: 'Technology',
          readTime: '5 min read',
        },
        {
          id: '2',
          title: 'Building a Successful Business Online',
          excerpt: 'Discover the strategies that helped thousands of entrepreneurs launch and grow their online businesses.',
          image: { src: '/assets/blog-2.jpg', alt: 'Business Growth' },
          author: 'Mike Chen',
          date: 'Nov 28, 2024',
          category: 'Business',
          readTime: '8 min read',
        },
        {
          id: '3',
          title: 'Design Trends That Will Shape 2024',
          excerpt: 'Explore the latest design trends and how to implement them in your next project.',
          image: { src: '/assets/blog-3.jpg', alt: 'Design Trends' },
          author: 'Emily Davis',
          date: 'Nov 25, 2024',
          category: 'Design',
          readTime: '6 min read',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'blog-7',
    name: 'Blog Timeline',
    type: 'blog',
    variant: 'timeline',
    thumbnail: '⏰',
    defaultData: {
      heading: 'Blog Timeline',
      description: 'Our journey through insights and discoveries',
      items: [
        {
          id: '1',
          title: 'Getting Started with Web Development in 2024',
          excerpt: 'Learn the essential tools and technologies you need to become a successful web developer this year.',
          image: { src: '/assets/blog-1.jpg', alt: 'Web Development' },
          author: 'Sarah Johnson',
          date: 'Dec 1, 2024',
          category: 'Technology',
          readTime: '5 min read',
        },
        {
          id: '2',
          title: 'Building a Successful Business Online',
          excerpt: 'Discover the strategies that helped thousands of entrepreneurs launch and grow their online businesses.',
          image: { src: '/assets/blog-2.jpg', alt: 'Business Growth' },
          author: 'Mike Chen',
          date: 'Nov 28, 2024',
          category: 'Business',
          readTime: '8 min read',
        },
        {
          id: '3',
          title: 'Design Trends That Will Shape 2024',
          excerpt: 'Explore the latest design trends and how to implement them in your next project.',
          image: { src: '/assets/blog-3.jpg', alt: 'Design Trends' },
          author: 'Emily Davis',
          date: 'Nov 25, 2024',
          category: 'Design',
          readTime: '6 min read',
        },
      ],
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // Contact Templates
  {
    id: 'contact-1',
    name: 'Contact Form',
    type: 'contact',
    variant: 'centered',
    thumbnail: '📧',
    defaultData: {
      heading: 'Get In Touch',
      description: 'Have a question? We\'d love to hear from you.',
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'contact-2',
    name: 'Contact with Info',
    type: 'contact',
    variant: 'split',
    thumbnail: '📱',
    defaultData: {
      heading: 'Let\'s Talk',
      description: 'Ready to start your project? Get in touch with us.',
      contactInfo: [
        { id: '1', icon: 'Mail', label: 'Email', value: 'hello@example.com' },
        { id: '2', icon: 'Phone', label: 'Phone', value: '+1 (555) 123-4567' },
        { id: '3', icon: 'MapPin', label: 'Location', value: 'San Francisco, CA' },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // Footer Templates
  {
    id: 'footer-1',
    name: 'Simple Footer',
    type: 'footer',
    variant: 'simple',
    thumbnail: '📄',
    defaultData: {
      logo: 'BuilderPro',
      description: 'Build beautiful websites with ease.',
      links: [
        { id: '1', text: 'Privacy', href: '#' },
        { id: '2', text: 'Terms', href: '#' },
        { id: '3', text: 'Contact', href: '#' },
      ],
      copyright: '© 2024 BuilderPro. All rights reserved.',
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '40px 24px',
    },
  },
  {
    id: 'footer-2',
    name: 'Multi-Column Footer',
    type: 'footer',
    variant: 'multi-column',
    thumbnail: '📚',
    defaultData: {
      logo: 'BuilderPro',
      description: 'The best website builder for modern creators.',
      columns: [
        {
          id: '1',
          title: 'Product',
          links: [
            { id: '1', text: 'Features', href: '#' },
            { id: '2', text: 'Pricing', href: '#' },
            { id: '3', text: 'Templates', href: '#' },
          ],
        },
        {
          id: '2',
          title: 'Company',
          links: [
            { id: '1', text: 'About', href: '#' },
            { id: '2', text: 'Blog', href: '#' },
            { id: '3', text: 'Careers', href: '#' },
          ],
        },
        {
          id: '3',
          title: 'Support',
          links: [
            { id: '1', text: 'Help Center', href: '#' },
            { id: '2', text: 'Contact', href: '#' },
            { id: '3', text: 'Status', href: '#' },
          ],
        },
      ],
      copyright: '© 2024 BuilderPro. All rights reserved.',
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
      padding: '60px 24px 40px',
    },
  },
  {
    id: 'footer-3',
    name: 'Minimal Footer',
    type: 'footer',
    variant: 'minimal',
    thumbnail: '📝',
    defaultData: {
      copyright: '© 2024 BuilderPro. All rights reserved.',
      backgroundColor: '#ffffff',
      textColor: '#666666',
      padding: '40px 24px',
    },
  },
  {
    id: 'footer-4',
    name: 'Centered Footer',
    type: 'footer',
    variant: 'centered',
    thumbnail: '🎯',
    defaultData: {
      logo: 'BuilderPro',
      description: 'Build beautiful websites with ease. Create stunning landing pages, portfolios, and business websites in minutes.',
      columns: [
        {
          id: '1',
          title: 'Product',
          links: [
            { id: '1', text: 'Features', href: '#' },
            { id: '2', text: 'Pricing', href: '#' },
            { id: '3', text: 'Templates', href: '#' },
          ],
        },
        {
          id: '2',
          title: 'Company',
          links: [
            { id: '1', text: 'About', href: '#' },
            { id: '2', text: 'Blog', href: '#' },
            { id: '3', text: 'Careers', href: '#' },
          ],
        },
        {
          id: '3',
          title: 'Support',
          links: [
            { id: '1', text: 'Help Center', href: '#' },
            { id: '2', text: 'Contact', href: '#' },
            { id: '3', text: 'Status', href: '#' },
          ],
        },
        {
          id: '4',
          title: 'Legal',
          links: [
            { id: '1', text: 'Privacy Policy', href: '#' },
            { id: '2', text: 'Terms of Service', href: '#' },
            { id: '3', text: 'Cookies', href: '#' },
          ],
        },
      ],
      copyright: '© 2024 BuilderPro. All rights reserved.',
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
      padding: '80px 24px 40px',
    },
  },
  {
    id: 'footer-5',
    name: 'Newsletter Footer',
    type: 'footer',
    variant: 'newsletter',
    thumbnail: '📧',
    defaultData: {
      logo: 'BuilderPro',
      description: 'The best website builder for modern creators.',
      columns: [
        {
          id: '1',
          title: 'Product',
          links: [
            { id: '1', text: 'Features', href: '#' },
            { id: '2', text: 'Pricing', href: '#' },
            { id: '3', text: 'Templates', href: '#' },
          ],
        },
        {
          id: '2',
          title: 'Company',
          links: [
            { id: '1', text: 'About', href: '#' },
            { id: '2', text: 'Blog', href: '#' },
            { id: '3', text: 'Careers', href: '#' },
          ],
        },
        {
          id: '3',
          title: 'Support',
          links: [
            { id: '1', text: 'Help Center', href: '#' },
            { id: '2', text: 'Contact', href: '#' },
            { id: '3', text: 'Status', href: '#' },
          ],
        },
        {
          id: '4',
          title: 'Legal',
          links: [
            { id: '1', text: 'Privacy Policy', href: '#' },
            { id: '2', text: 'Terms of Service', href: '#' },
            { id: '3', text: 'Cookies', href: '#' },
          ],
        },
      ],
      copyright: '© 2024 BuilderPro. All rights reserved.',
      backgroundColor: '#f8f9fa',
      textColor: '#000000',
      padding: '80px 24px 40px',
    },
  },
  {
    id: 'footer-6',
    name: 'Dark Footer',
    type: 'footer',
    variant: 'dark',
    thumbnail: '🌙',
    defaultData: {
      logo: 'BuilderPro',
      description: 'Build beautiful websites with ease.',
      columns: [
        {
          id: '1',
          title: 'Product',
          links: [
            { id: '1', text: 'Features', href: '#' },
            { id: '2', text: 'Pricing', href: '#' },
            { id: '3', text: 'Templates', href: '#' },
          ],
        },
        {
          id: '2',
          title: 'Company',
          links: [
            { id: '1', text: 'About', href: '#' },
            { id: '2', text: 'Blog', href: '#' },
            { id: '3', text: 'Careers', href: '#' },
          ],
        },
      ],
      copyright: '© 2024 BuilderPro. All rights reserved.',
      backgroundColor: '#000000',
      textColor: '#ffffff',
      padding: '80px 24px 40px',
    },
  },

  // Testimonials Templates
  {
    id: 'testimonials-1',
    name: 'Testimonials Grid',
    type: 'testimonials',
    variant: 'grid',
    thumbnail: '💬',
    defaultData: {
      heading: 'What Our Customers Say',
      description: 'Don\'t just take our word for it - hear from our satisfied customers.',
      items: [
        {
          id: '1',
          quote: 'This platform has transformed how we build websites. The drag-and-drop interface is incredibly intuitive.',
          name: 'Sarah Johnson',
          role: 'Marketing Director',
          image: { src: '/assets/testimonial-1.jpg', alt: 'Sarah Johnson' },
        },
        {
          id: '2',
          quote: 'The templates are beautiful and the customization options are endless. Highly recommended!',
          name: 'Mike Chen',
          role: 'Startup Founder',
          image: { src: '/assets/testimonial-2.jpg', alt: 'Mike Chen' },
        },
        {
          id: '3',
          quote: 'We launched our new website in record time. The support team was incredibly helpful throughout.',
          name: 'Emily Davis',
          role: 'Product Manager',
          image: { src: '/assets/testimonial-3.jpg', alt: 'Emily Davis' },
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'testimonials-2',
    name: 'Testimonials Carousel',
    type: 'testimonials',
    variant: 'carousel',
    thumbnail: '🎠',
    defaultData: {
      heading: 'Customer Success Stories',
      description: 'Real results from real customers who chose our platform.',
      items: [
        {
          id: '1',
          quote: 'The analytics and insights provided have helped us optimize our conversion rates significantly.',
          name: 'David Wilson',
          role: 'E-commerce Manager',
          image: { src: '/assets/testimonial-4.jpg', alt: 'David Wilson' },
        },
        {
          id: '2',
          quote: 'Outstanding customer service and reliable platform. We couldn\'t be happier with our choice.',
          name: 'Lisa Rodriguez',
          role: 'Business Owner',
          image: { src: '/assets/testimonial-5.jpg', alt: 'Lisa Rodriguez' },
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'testimonials-3',
    name: 'Testimonials Cards',
    type: 'testimonials',
    variant: 'cards',
    thumbnail: '🃏',
    defaultData: {
      heading: 'Customer Reviews',
      description: 'See what our customers are saying about their experience.',
      items: [
        {
          id: '1',
          quote: 'This platform has transformed how we build websites. The drag-and-drop interface is incredibly intuitive.',
          name: 'Sarah Johnson',
          role: 'Marketing Director',
          company: 'TechCorp',
          image: { src: '/assets/testimonial-1.jpg', alt: 'Sarah Johnson' },
        },
        {
          id: '2',
          quote: 'The templates are beautiful and the customization options are endless. Highly recommended!',
          name: 'Mike Chen',
          role: 'Startup Founder',
          company: 'InnovateLabs',
          image: { src: '/assets/testimonial-2.jpg', alt: 'Mike Chen' },
        },
        {
          id: '3',
          quote: 'We launched our new website in record time. The support team was incredibly helpful throughout.',
          name: 'Emily Davis',
          role: 'Product Manager',
          company: 'DataFlow Inc',
          image: { src: '/assets/testimonial-3.jpg', alt: 'Emily Davis' },
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'testimonials-4',
    name: 'Minimal Testimonials',
    type: 'testimonials',
    variant: 'minimal',
    thumbnail: '✨',
    defaultData: {
      heading: 'What People Say',
      description: 'Honest feedback from our community.',
      items: [
        {
          id: '1',
          quote: 'Simply amazing. Changed everything for us.',
          name: 'Alex Rivera',
          role: 'Designer',
          image: { src: '/assets/testimonial-1.jpg', alt: 'Alex Rivera' },
        },
        {
          id: '2',
          quote: 'Best decision we made this year. Highly recommend.',
          name: 'Jordan Kim',
          role: 'Developer',
          image: { src: '/assets/testimonial-2.jpg', alt: 'Jordan Kim' },
        },
        {
          id: '3',
          quote: 'Intuitive, powerful, and reliable. Perfect combination.',
          name: 'Taylor Morgan',
          role: 'Entrepreneur',
          image: { src: '/assets/testimonial-3.jpg', alt: 'Taylor Morgan' },
        },
      ],
      backgroundColor: '#fafafa',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'testimonials-5',
    name: 'Testimonials with Ratings',
    type: 'testimonials',
    variant: 'ratings',
    thumbnail: '⭐',
    defaultData: {
      heading: 'Rated 5 Stars by Our Customers',
      description: 'Join thousands of satisfied customers who trust our platform.',
      items: [
        {
          id: '1',
          quote: 'This platform has transformed how we build websites. The drag-and-drop interface is incredibly intuitive.',
          name: 'Sarah Johnson',
          role: 'Marketing Director',
          company: 'TechCorp',
          rating: 5,
          image: { src: '/assets/testimonial-1.jpg', alt: 'Sarah Johnson' },
        },
        {
          id: '2',
          quote: 'The templates are beautiful and the customization options are endless. Highly recommended!',
          name: 'Mike Chen',
          role: 'Startup Founder',
          company: 'InnovateLabs',
          rating: 5,
          image: { src: '/assets/testimonial-2.jpg', alt: 'Mike Chen' },
        },
        {
          id: '3',
          quote: 'We launched our new website in record time. The support team was incredibly helpful throughout.',
          name: 'Emily Davis',
          role: 'Product Manager',
          company: 'DataFlow Inc',
          rating: 5,
          image: { src: '/assets/testimonial-3.jpg', alt: 'Emily Davis' },
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'testimonials-6',
    name: 'Video Testimonials',
    type: 'testimonials',
    variant: 'video',
    thumbnail: '🎥',
    defaultData: {
      heading: 'Hear From Our Customers',
      description: 'Watch real customers share their success stories.',
      items: [
        {
          id: '1',
          quote: 'This platform has transformed how we build websites. The drag-and-drop interface is incredibly intuitive.',
          name: 'Sarah Johnson',
          role: 'Marketing Director',
          company: 'TechCorp',
          videoUrl: 'https://example.com/video1.mp4',
          thumbnail: { src: '/assets/testimonial-1.jpg', alt: 'Sarah Johnson' },
        },
        {
          id: '2',
          quote: 'The templates are beautiful and the customization options are endless. Highly recommended!',
          name: 'Mike Chen',
          role: 'Startup Founder',
          company: 'InnovateLabs',
          videoUrl: 'https://example.com/video2.mp4',
          thumbnail: { src: '/assets/testimonial-2.jpg', alt: 'Mike Chen' },
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // Pricing Templates
  {
    id: 'pricing-1',
    name: '3-Column Pricing',
    type: 'pricing',
    variant: 'three-column',
    thumbnail: '💰',
    defaultData: {
      heading: 'Choose Your Plan',
      description: 'Select the perfect plan for your needs. Upgrade or downgrade at any time.',
      items: [
        {
          id: '1',
          name: 'Starter',
          price: '9',
          period: 'month',
          description: 'Perfect for small projects',
          features: [
            'Up to 5 pages',
            'Basic templates',
            'Email support',
            'Mobile responsive',
          ],
          buttonText: 'Get Started',
        },
        {
          id: '2',
          name: 'Professional',
          price: '29',
          period: 'month',
          description: 'For growing businesses',
          popular: true,
          features: [
            'Unlimited pages',
            'Premium templates',
            'Priority support',
            'Advanced analytics',
            'Custom domain',
          ],
          buttonText: 'Go Professional',
        },
        {
          id: '3',
          name: 'Enterprise',
          price: '99',
          period: 'month',
          description: 'For large organizations',
          features: [
            'Everything in Professional',
            'White-label solution',
            'Dedicated account manager',
            'Advanced integrations',
            'Custom development',
          ],
          buttonText: 'Contact Sales',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'pricing-2',
    name: '2-Column Pricing',
    type: 'pricing',
    variant: 'two-column',
    thumbnail: '⚖️',
    defaultData: {
      heading: 'Simple Pricing',
      description: 'Two plans, everything you need.',
      items: [
        {
          id: '1',
          name: 'Basic',
          price: '19',
          period: 'month',
          description: 'Essential features for individuals',
          features: [
            '10 projects',
            'Basic templates',
            'Community support',
            'Standard exports',
          ],
          buttonText: 'Start Basic',
        },
        {
          id: '2',
          name: 'Premium',
          price: '49',
          period: 'month',
          description: 'Advanced features for teams',
          popular: true,
          features: [
            'Unlimited projects',
            'Premium templates',
            'Priority support',
            'Advanced exports',
            'Team collaboration',
          ],
          buttonText: 'Go Premium',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // FAQ Templates
  {
    id: 'faq-1',
    name: 'FAQ Accordion',
    type: 'faq',
    variant: 'accordion',
    thumbnail: '❓',
    defaultData: {
      heading: 'Frequently Asked Questions',
      description: 'Everything you need to know about our platform.',
      items: [
        {
          id: '1',
          question: 'How easy is it to get started?',
          answer: 'Getting started is incredibly simple. Just sign up for an account, choose a template, and start customizing. No coding knowledge required.',
        },
        {
          id: '2',
          question: 'Can I export my website?',
          answer: 'Yes! You can export your website as HTML/CSS files or publish directly to our hosting platform.',
        },
        {
          id: '3',
          question: 'Do you offer customer support?',
          answer: 'Absolutely. We provide 24/7 customer support through email, live chat, and our comprehensive help center.',
        },
        {
          id: '4',
          question: 'Can I upgrade my plan later?',
          answer: 'Yes, you can upgrade or downgrade your plan at any time. Changes take effect immediately.',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'faq-2',
    name: 'FAQ Grid',
    type: 'faq',
    variant: 'grid',
    thumbnail: '🔲',
    defaultData: {
      heading: 'Common Questions',
      description: 'Find answers to the most frequently asked questions.',
      items: [
        {
          id: '1',
          question: 'What payment methods do you accept?',
          answer: 'We accept all major credit cards, PayPal, and bank transfers for annual plans.',
        },
        {
          id: '2',
          question: 'Is there a free trial?',
          answer: 'Yes! We offer a 14-day free trial with full access to all features.',
        },
        {
          id: '3',
          question: 'Can I cancel anytime?',
          answer: 'Yes, you can cancel your subscription at any time with no cancellation fees.',
        },
        {
          id: '4',
          question: 'Do you offer refunds?',
          answer: 'We offer a 30-day money-back guarantee on all paid plans.',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },

  // Team Templates
  {
    id: 'team-1',
    name: 'Team Grid',
    type: 'team',
    variant: 'grid',
    thumbnail: '👥',
    defaultData: {
      heading: 'Meet Our Team',
      description: 'The passionate people behind our success.',
      items: [
        {
          id: '1',
          name: 'Alex Thompson',
          role: 'CEO & Founder',
          bio: 'Visionary leader with 10+ years in tech entrepreneurship.',
          image: { src: '/assets/team-1.jpg', alt: 'Alex Thompson' },
          email: 'alex@company.com',
          linkedin: 'https://linkedin.com/in/alexthompson',
        },
        {
          id: '2',
          name: 'Maria Garcia',
          role: 'Head of Design',
          bio: 'Award-winning designer passionate about user experience.',
          image: { src: '/assets/team-2.jpg', alt: 'Maria Garcia' },
          email: 'maria@company.com',
          linkedin: 'https://linkedin.com/in/mariagarcia',
        },
        {
          id: '3',
          name: 'James Wilson',
          role: 'Lead Developer',
          bio: 'Full-stack developer with expertise in modern web technologies.',
          image: { src: '/assets/team-3.jpg', alt: 'James Wilson' },
          email: 'james@company.com',
          linkedin: 'https://linkedin.com/in/jameswilson',
        },
      ],
      backgroundColor: '#f1f5f9',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
  {
    id: 'team-2',
    name: 'Team List',
    type: 'team',
    variant: 'list',
    thumbnail: '📋',
    defaultData: {
      heading: 'Our Leadership',
      description: 'Experienced professionals driving innovation.',
      items: [
        {
          id: '1',
          name: 'Sarah Chen',
          role: 'VP of Product',
          bio: 'Product strategist focused on building products that customers love.',
          image: { src: '/assets/team-4.jpg', alt: 'Sarah Chen' },
          email: 'sarah@company.com',
          linkedin: 'https://linkedin.com/in/sarahchen',
        },
        {
          id: '2',
          name: 'Robert Kim',
          role: 'Head of Marketing',
          bio: 'Marketing expert with a track record of driving growth.',
          image: { src: '/assets/team-5.jpg', alt: 'Robert Kim' },
          email: 'robert@company.com',
          linkedin: 'https://linkedin.com/in/robertkim',
        },
      ],
      backgroundColor: '#ffffff',
      textColor: '#000000',
      padding: '80px 24px',
    },
  },
];

